site_name: CAVEclient
site_url: https://caveconnectome.github.io/CAVEclient/
repo_url: https://github.com/CAVEconnectome/CAVEclient/
repo_name: CAVEconnectome/CAVEclient
edit_uri: edit/master/docs/
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial:
    - tutorials/index.md
    - tutorials/framework.md
    - tutorials/authentication.md
    - tutorials/annotation.md
    - tutorials/chunkedgraph.md
    - tutorials/l2cache.md
    - tutorials/info.md
    - tutorials/schemas.md
    - tutorials/state.md
    - tutorials/materialization.md
  - Client API: # these match the client property names
    - client_api/index.md
    - client_api/client.md
    - client_api/annotation.md
    - client_api/auth.md
    - client_api/chunkedgraph.md
    - client_api/info.md
    - client_api/l2cache.md
    - client_api/materialize.md
    - client_api/schema.md
    - client_api/state.md
  - Extended API: # these match the python file names
    - extended_api/index.md
    - extended_api/annotationengine.md
    - extended_api/auth.md
    - extended_api/base.md
    - extended_api/chunkedgraph.md
    - extended_api/datastack_lookup.md
    - extended_api/emannotationschemas.md
    - extended_api/framework.md
    - extended_api/infoservice.md
    - extended_api/jsonservice.md
    - extended_api/l2cache.md
    - extended_api/materializationengine.md
    - extended_api/session_config.md
  - Glossary: glossary.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  logo: images/logo-cleanest.png
  favicon: images/logo-cleanest.png
  palette:
    scheme: preference
    primary: black
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.footer
    # - navigation.path
    - navigation.prune
    # - navigation.sections # toggle to have sections in side nav
    - navigation.tabs # toggle to mainly use top nav
    - navigation.tabs.sticky
    - content.action.edit
    - content.action.view
    - toc.follow
    - toc.integrate # whether to include the toc in the main nav bar to the left
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/pandas-docs/stable/objects.inv
            - https://networkx.org/documentation/stable/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv
            - https://requests.readthedocs.io/en/latest/objects.inv
          options:
            show_source: false
            docstring_style: numpy
            docstring_section_style: table # list, table, spacy
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: true
            allow_section_blank_line: false
            show_root_heading: false
            show_root_toc_entry: false
            show_object_full_path: false
            show_symbol_type_heading: false # whether to show "meth/func/etc" in the page
            show_symbol_type_toc: false # whether to show "meth/func/etc" in the toc
            signature_crossrefs: true # https://mkdocstrings.github.io/python/usage/configuration/signatures/#signature_crossrefs
            members_order: alphabetical # can be source
            group_by_category: true  # order is attributes, classes, functions, modules
            summary: true
            show_if_no_docstring: false
            show_docstring_attributes: false
            annotations_path: brief # https://mkdocstrings.github.io/python/usage/configuration/signatures/#annotations_path
            show_signature: true
            separate_signature: false
            show_signature_annotations: false
            unwrap_annotated: false # https://mkdocstrings.github.io/python/usage/configuration/signatures/#unwrap_annotated
            heading_level: 2
            inherited_members: true
  - macros
  - autorefs
  - section-index
  # - git-authors: # this one is more email-based
  #     show_contribution: true
  #     authorship_threshold_percent: 5
  # - git-committers: 
      # repository: seung-lab/CAVEclient
      # branch: main
  # - git-revision-date-localized:
  #     enable_creation_date: true
  # - social:
  #     cards_layout: default

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seung-lab/CAVEclient
      name: Github
  version:
    provider: mike
  names: 
    repo_title: CAVEclient
    package: caveclient
    main_branch: master
  client_api_paths:
    annotation: ../client_api/annotation.md#caveclient.annotationengine.AnnotationClientV2
    auth: ../client_api/auth.md#caveclient.auth.AuthClient
    chunkedgraph: ../client_api/chunkedgraph.md#caveclient.chunkedgraph.ChunkedGraphClientV1
    materialize: ../client_api/materialize.md#caveclient.materializationengine.MaterializationClientV3
    l2cache: ../client_api/l2cache.md#caveclient.l2cache.L2CacheClientLegacy
    state: ../client_api/state.md#caveclient.state.JSONServiceV1

watch:
  - caveclient/
  - docs/
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
