name: Lint and Format
on:
  push:
    branches:
      - master
  pull_request:
    branches: master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows other workflows to trigger this workflow
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: check --fix
      - uses: chartboost/ruff-action@v1
        with:
          args: format
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style fixes by ruff"
