name: Lint and Format
on:
  push:
    branches:
      - master
  pull_request:
    branches: master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows other workflows to trigger this workflow
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.5.2"
      - name: Set up environment
        run: uv sync --python 3.11
      - name: Run format checks
        run: uvx --from poethepoet poe lint
